package detribus;

import haxel.HxlGame;
import haxel.HxlState;
import haxel.HxlGraphics;
import haxel.HxlSprite;
import haxel.HxlPoint;
import haxel.HxlTilemap;
import haxel.HxlTileblock;
import haxel.HxlAnim;
import haxel.HxlSound;
import haxel.HxlText;
import haxel.HxlTextInput;
import haxel.HxlMouse;
import haxel.HxlKeyboard;
import haxel.HxlPause;
import haxel.HxlPreloader;
import haxel.HxlTimer;
import haxel.HxlButton;
import haxel.HxlEmitter;
import haxel.HxlPreloader;
import haxel.HxlList;
import haxel.HxlQuadTree;
import haxel.HxlFlash;
import haxel.HxlQuake;
import haxel.HxlFade;
import haxel.HxlUtil;
import haxel.HxlSave;

typedef HxlGame = haxel.HxlGame;
typedef HxlState = haxel.HxlState;
typedef HxlGraphics = haxel.HxlGraphics;
typedef HxlPoint = haxel.HxlPoint;
typedef HxlSprite = haxel.HxlSprite;
typedef HxlTilemap = haxel.HxlTilemap;
typedef HxlTileblock = haxel.HxlTileblock;
typedef HxlTile = haxel.HxlTile;
typedef Visibility = haxel.Visibility;
typedef HxlAnim = haxel.HxlAnim;
typedef HxlSound = haxel.HxlSound;
typedef HxlText = haxel.HxlText;
typedef HxlTextInput = haxel.HxlTextInput;
typedef HxlMouse = haxel.HxlMouse;
typedef HxlKeyboard = haxel.HxlKeyboard;
typedef HxlPause = haxel.HxlPause;
typedef HxlPreloader = haxel.HxlPreloader;
typedef HxlTimer = haxel.HxlTimer;
typedef HxlButton = haxel.HxlButton;
typedef HxlEmitter = haxel.HxlEmitter;
typedef HxlList = haxel.HxlList;
typedef HxlQuadTree = haxel.HxlQuadTree;
typedef HxlFlash = haxel.HxlFlash;
typedef HxlQuake = haxel.HxlQuake;
typedef HxlFade = haxel.HxlFade;
typedef HxlUtil = haxel.HxlUtil;
typedef HxlSave = haxel.HxlSave;