// cqTextEmbed.cpp : Defines the entry point for the console application.
//

#include <Windows.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

char *header =
"// THIS FILE IS AUTOMATICALLY GENERATED FROM TEXT FILES IN /BIN. DO NOT MODIFY\r\
package data;\r\
\r\
/**\r\
 * ...\r\
 * @author randomnine\r\
 */\r\
\r\
class StatsFileEmbed \r\
{\r\
	public static function loadEmbeddedFiles() \r\
	{\r\
		var embedText:String;\r\
		var embedFile:StatsFile;\r\
\r\
";

char *fileEmbed1 =
"		embedText = \"";

char *fileEmbed2 = "\";\r\
		embedFile = StatsFile.loadFromString( \"";

char *fileEmbed3 = "\", embedText );\r\
\r\
";

char *footer =
"	}\r\
}\r\
";

void strwcat( char *_out, TCHAR *_in )
{
	char *write = _out + strlen( _out );

	while ( *_in != L'\0' )
	{
		*write = (char)(*_in);
		++write;
		++_in;
	}

	*write = '\0';
}

int main(int argc, char* argv[])
{
	char *output = new char[100000]; // 100KB max.

	// Write header.
	strcpy( output, header );

	// Read all from "bin/*.txt".
	HANDLE fh;
	WIN32_FIND_DATA *fd = new WIN32_FIND_DATA();
	fh = FindFirstFile( L"bin/*.txt", fd );

	if ( fh != INVALID_HANDLE_VALUE )
	{
		do
		{
			char filepath[256] = "bin/";
			strwcat( filepath, fd->cFileName );

			FILE *f_in = fopen( filepath, "r" );

			if ( f_in != NULL )
			{
				strcat( output, fileEmbed1 );

				char buf[512];
				while ( fgets( buf, 512, f_in ) )
				{
					strcat( output, buf );
				}

				fclose( f_in );

				strcat( output, fileEmbed2 );
				strwcat( output, fd->cFileName );
				strcat( output, fileEmbed3 );
			}
		} while ( FindNextFile( fh, fd ) );
	}

	// Add footer.
	strcat( output, footer );

	// Write to "src/data/StatsFileEmbed.hx".
	FILE *f_out = fopen( "src/data/StatsFileEmbed.hx", "w" );
	fwrite( output, 1, strlen(output), f_out );
	fclose( f_out );

	delete fd;
	delete [] output;

	return 0;
}
