// THIS FILE IS AUTOMATICALLY GENERATED FROM TEXT FILES IN /BIN. DO NOT MODIFYpackage data;/** * ... * @author randomnine */class StatsFileEmbed {	public static function loadEmbeddedFiles() 	{		var embedText:String;		var embedFile:StatsFile;		embedText = "Field String ID
Field String Sprite
Field Int Portrait
Field String EntryBG
Field Int DamagePref
Field Int AttackPref
Field Int DefensePref
Field Int SpeedPref
Field Int SpiritPref
Field Int LifePref
Field String Item1
Field String Item2
Field String Item3
Field String Item4
Field String Item5
Field String Item6

; ID    Sprite  Prt EntryBG            Dmg Atk Def Spd Spr Lif Items
FIGHTER fighter   1 SpriteKnightEntry   80 100 100  90  25  50 LEATHER_ARMOR SHORT_SWORD BERSERK    RED_POTION RED_POTION BLUE_POTION
WIZARD  wizard    2 SpriteWizardEntry   25  50  50 200 300 100 STAFF         FIREBALL    RED_POTION PURPLE_POTION PURPLE_POTION
THIEF   thief     0 SpriteThiefEntry    55 100  50 200  50  50 DAGGER        SHADOW_WALK RED_POTION RED_POTION YELLOW_POTION GREEN_POTION
";		embedFile = StatsFile.loadFromString( "classes.txt", embedText );		embedText = "Field String ID
Field Int Level
Field Int Attack
Field Int Defense
Field Int Speed
Field Int Spirit
Field Int Vitality
Field Int HP

; ID    Lvl Atk Def Spd Spr Vit HP
FIGHTER   1   5   3   5   1   4 12
FIGHTER   2   5   3   5   1   4 16
FIGHTER   3   5   3   5   1   4 20
FIGHTER   4   5   3   5   1   4 24
FIGHTER   5   5   3   5   1   4 28
FIGHTER   6   5   3   5   1   4 32
FIGHTER   7   5   3   5   1   4 36
FIGHTER   8   5   3   5   1   4 40
FIGHTER   9   5   3   5   1   4 44

WIZARD    1   2   2   6   4   2  8
WIZARD    2   2   2   6   4   2 10
WIZARD    3   2   2   6   4   2 12
WIZARD    4   2   2   6   4   2 14
WIZARD    5   2   2   6   4   2 16
WIZARD    6   2   2   6   4   2 18
WIZARD    7   2   2   6   4   2 20
WIZARD    8   2   2   6   4   2 22
WIZARD    9   2   2   6   4   2 24

THIEF     1   3   3  10   3   3  6
THIEF     2   3   3  10   3   3  9
THIEF     3   3   3  10   3   3 12
THIEF     4   3   3  10   3   3 15
THIEF     5   3   3  10   3   3 18
THIEF     6   3   3  10   3   3 21
THIEF     7   3   3  10   3   3 24
THIEF     8   3   3  10   3   3 27
THIEF     9   3   3  10   3   3 30";		embedFile = StatsFile.loadFromString( "classStats.txt", embedText );		embedText = "Field String ID
Field String Data

; Cutscenes!
\"AsterionIntro\"    \"ある静かな夜、平和なハレモットの町に、\nミノタウロスのアステリオンが降り立った。ヤツは人の苦悩を悦びとし、多くの住民は\n殺し、生き残った者を奴隷とした。\n\nそれから何年もの時が過ぎた。\n今なお、ヤツは人を苦しめて、そのこと\nに愉悦を感じている。洞窟の奥深くで、子分とともに奪い取った財宝を貯め込み、\n暮らしているのだ。\n\nかつてこの町から逃げだした者がいる。\nそれがキミだ。復讐の時のため、\n力を蓄えてきた。さあ、今こそ町をヤツらの支配から解放する時だ。\"

\"AsterionDefeated\"    \"最後の敵を斬りつけると、ついに\nアステリオンが姿を現した。ヤツは\nショーに満足したかのように、\n猛々しい笑い声を発して近づいてくる。\nそして、いにしえの呪文を唱えた。\n\n突然現れた揺らめく門に、ヤツは足を\n踏み入れ、姿を消した。そう、キミは\nミノタウロスを追い払ったのだ！\nハレモットに再び平和を\n取り戻したのだ！\n\n――つかの間の平和を。\"

; Classes.
\"FIGHTER\"    \"無比の体力と気力を持った屈強な戦士。\n戦場でのハックアンドスラッシュを得意とし、\nその戦いぶりはほれぼれするほど。\n\n初心者にオススメ。\"
\"WIZARD\"     \"思慮深い賢者。秘密を知る者、奇跡を起こす者、神秘的な魔術の熟練者。そして、おいしいミックスドリンクもお手の物。\n\n呪文を素早く使えるため、積極的に使っていこう。\"
\"THIEF\"      \"狡猾で機敏な悪党。唯一の信条は、生き延びること、\nただそれだけである。\n\n最も扱いの難しいキャラクター。\nスピードとスキルを使って攻撃を避けよう。\"

; Class entry blurb.
\"SpriteKnightEntry\"    \"輝く剣とともに、キミは憎き\nミノタウロスの陰鬱な住みかへと\n足を踏み入れる。やつの歪んだ邪悪な家来たちの下卑た笑い声が空間を満たしている。\n\nキミは微笑む。もうすぐ、その笑い声を止められるのだから。\"
\"SpriteWizardEntry\"    \"苦悩に満ちた死者の魂が\nミノタウロスの悪行を囁きかける。\nキミは跪き、改めて復讐を誓う。\n\n神秘の炎がキミの手のひらの上で\n踊る。卑劣なヤツらを葬ることが、\n彼らへの慰めとなるだろう。\"
\"SpriteThiefEntry\"    \"キミは灯りのない階段を、足音を\n立てずに下りていく。ミノタウロスのしもべたちは、誰一人としてキミの侵入に気付いていない。\n\nヤツらがもうすぐ手放すことになる大量の財宝のことを思うと、笑みをこぼさずにはいられない。\"

; Stats.
ATTRIBUTES  \"(詳細を見るにはパラメータに\nマウスオーバー。)\"
HEALTH      \"体力:ヒットポイント。\"
ATTACK      \"攻撃力:武器攻撃が\n成功する確率を示す。\"
DEFENSE     \"防御力:ダメージに耐える\n確率を示す。\"
SPEED       \"スピード:敵に比べて、どれぐらい\n速く行動ができるかを示す。\"
SPIRIT      \"精神:ほぼすべての呪文において、\nリチャージする速度を示す。\"
VITALITY    \"活力:レベルアップ時に得られる\nヒットポイントの増加値を示す。\"

; Potions.
RED_POTION       \"赤い膏薬が入った、小さなガラス瓶。香りが良く、\n使用すると体力が\n回復する。\"
PURPLE_POTION    \"興奮した神経を鎮める、\nさわやかな飲料。呪文を\nチャージできる。\"
GREEN_POTION     \"一時的に超人的な攻撃力と反射神経を与える。\"
BLUE_POTION      \"一時的に使用者の肉体をぶ厚い皮で守る。\"
YELLOW_POTION    \"がぶ飲みすると、とてつもないスピードで動けるようになる謎の飲料。\"

; Boots.
BOOTS            \"品質の高い革のブーツ。\nより速く動ける\nようになる。\"
WINGED_SANDALS   \"不朽の黄金でつくられた、\n履いた者に鳥のような\n敏捷性を与える\n羽根つきのサンダル。\"
TUNDRA_BOOTS     \"苛酷な環境に最適化\nされたブーツ。あらゆる地形で\n優れた機動性を発揮できる。\"

; Armor.
LEATHER_ARMOR    \"ワックスで煮込んだ革で\nつくられた、頑強な鎧。\"
BREASTPLATE      \"機動性を損なうことなく\n臓器を守り抜く、\n鉄製の胸当て。\"
CLOAK            \"魔法の布で織られた、丈夫なクローク。袖を通すと、空にふれているような\n気持ちになるほど軽い。\"
FULL_PLATE_MAIL  \"世界中の騎士から高い評価を受け続けてきた伝統的な甲冑。\"

; Jewelry.
RING             \"小さな銀のリング。装着者に神秘的な知性を与えてくれる。\"
AMULET           \"シンプルなアミュレットだが、には悟りが浸み込まれており、装着者に神々の精神を与える。\"
GEMMED_AMULET    \"ルーンの紋章が刻まれた\nアミュレット。装着すると、様々な加護がもたらされる。\"
GEMMED_RING      \"生命力に満ち溢れたリング。強力なオーラが得られる。\"

; Hats.
CAP              \"頭を保護する鉄製の\nキャップ。さらに上から\nオシャレな帽子も\nかぶれる。\"
HELM             \"ロシャッゴン鉱山で\nドワーフたちの手によって\nつくられた兜。鍛冶師が\n代々受け継ぐ秘密の\n合金が使用されている。\"
FULL_HELM        \"闇の僧侶たちが愛用していた兜。満月の力を取り込むことができる。\"
GOLDEN_HELM      \"純金で造られた兜。決して傷つくことなく、何よりルックスが豪華。\"

; Gloves.
GLOVE            \"身につけると、より素早く動けるようになる手甲。\"
BRACELET         \"偉大な戦士の精神が\n封じ込められた魔法の\nブレスレット。\"
GAUNTLET         \"細部にこだわって装飾が\n施されたガントレット。\"

; Weapons.
DAGGER           \"刺したり突いたりするための諸刃のナイフ。\"
SHORT_SWORD      \"柄が取りつけられた刃渡り約60cmの片手用の刃。\"
STAFF            \"頑丈な硬材の柄の先端に、金属が取りつけられた\n武器。\"
LONG_SWORD       \"長い十字の柄がついた、\n刀身1メートル以上の長剣。\"
AXE              \"木や肉を叩き斬る際に用いられる、強力な斧。\"
BATTLE_AXE       \"最高級の金属から造られた斧。突き、切り裂き、強打と臨機応変に使用可能。\"
RUNE_SWORD       \"神秘のエネルギーが\n脈打つ、見事な造形の剣。\"
MACE             \"先端の尖った巨大な矛。\n振り回して、強力な一撃を\n与えられる。\"
CLAYMORE         \"古代の武器。この剣がもたらした数々の栄光は、今なお吟遊詩人たちに歌い継がれている。\"
BROAD_SWORD      \"最高の技術を持つ\n極東の刀鍛冶師による、\n優雅な武器。\"

; Spells.
BERSERK          \"狂暴化し、攻撃力と\nスピードを増幅させる。\n\n攻撃することで\nリチャージされる。\"
BLESS_WEAPON     \"装備中の武器に\n恩恵を与え、一時的に\nダメージを高める。\"
HASTE            \"より速くより敏捷にする。\"
SHADOW_WALK      \"数秒間、あなたを\n透明にする。\n\n行動することで\nリチャージされる。\"
STONE_SKIN       \"皮膚を硬化させ、防御力を高める。ただし、動きは鈍くなる。\"
BLINK            \"ランダムの目的地に\n移動する。\"
MAGIC_ARMOR      \"魔法のオーラで、\n魔法防御を高める。\"
PASS_WALL        \"壁を通り抜けられるようになる。\"
REVEAL_MAP       \"現フロアのレイアウトを\n明らかにする。\"
HEAL             \"体力と気力を回復する。\n\n経験値を獲得することで\nリチャージされる。\"

FREEZE           \"一定時間、敵の動きを\n遅くする。\"
FIREBALL         \"爆発する炎の玉をぶつけ、ダメージを与える。\"
ENFEEBLE_MONSTER \"敵を弱体化し、\n危険を回避する。\"
CHARM_MONSTER    \"敵を魅了し、一時的に\n味方にする。\"
POLYMORPH        \"敵を別の敵に変化させる。\"
SLEEP            \"敵を眠らせる。\"
FEAR             \"敵が恐怖に陥り、\n逃げ出すようになる。\"
MAGIC_MIRROR     \"分身を生みだし、\n敵の気を逸らす。\"
TELEPORT         \"好きな場所に移動する。\"
";		embedFile = StatsFile.loadFromString( "descriptions.txt", embedText );		embedText = "Field String ID
Field String Sprite
Field String Slot
Field Int LevelMin
Field Int LevelMax
Field Int Weight
Field Int DamageMin
Field Int DamageMax
Field String Buff1
Field Int Buff1Val
Field String Buff2
Field Int Buff2Val

; ID            Sprite          Slot    Lv- Lv+ Wgt Dmg- Dmg+ Buff1   V1 Buff2   V2 
BOOTS           boots           SHOES     1   1 100    0    0 speed    1
WINGED_SANDALS  winged_sandals  SHOES     3   4 100    0    0 speed    2
TUNDRA_BOOTS    tundra_boots    SHOES     7  99 100    0    0 speed    2 defense  1

; ID            Sprite          Slot    Lv- Lv+ Wgt Dmg- Dmg+ Buff1   V1 Buff2   V2 
LEATHER_ARMOR   leather_armor   ARMOR     1   1 100    0    0 defense  1
BREASTPLATE     breastplate     ARMOR     2   3 100    0    0 defense  2
CLOAK           cloak           ARMOR     5   6 100    0    0 defense  2 speed    2
FULL_PLATE_MAIL full_plate_mail ARMOR     7  99 100    0    0 defense  4

; ID            Sprite          Slot    Lv- Lv+ Wgt Dmg- Dmg+ Buff1   V1 Buff2   V2 
RING            ring            JEWELRY   2   3 100    0    0 spirit   1
AMULET          amulet          JEWELRY   4   5 100    0    0 spirit   2
GEMMED_AMULET   gemmed_amulet   JEWELRY   6   7 100    0    0 spirit   2 defense  2
GEMMED_RING     gemmed_ring     JEWELRY   8  99 100    0    0 life     3 spirit   2

; ID            Sprite          Slot    Lv- Lv+ Wgt Dmg- Dmg+ Buff1   V1 Buff2   V2 
CAP             cap             HAT       1   2 100    0    0 life     1
HELM            helm            HAT       4   5 100    0    0 life     2
FULL_HELM       full_helm       HAT       6   7 100    0    0 life     4
GOLDEN_HELM     golden_helm     HAT       8  99 100    0    0 life     2 defense  3

; ID            Sprite          Slot    Lv- Lv+ Wgt Dmg- Dmg+ Buff1   V1 Buff2   V2 
GLOVE           glove           GLOVES    1   2 100    0    0 attack   1
BRACELET        bracelet        GLOVES    3   4 100    0    0 attack   2
GAUNTLET        gauntlet        GLOVES    6   7 100    0    0 attack   2 defense  2

; ID            Sprite          Slot    Lv- Lv+ Wgt Dmg- Dmg+ Buff1   V1 Buff2   V2 
DAGGER          dagger          WEAPON    1   1 100    1    2
SHORT_SWORD     short_sword     WEAPON    1   2 100    1    3
STAFF           staff           WEAPON    2   3 100    1    3 spirit   1
LONG_SWORD      long_sword      WEAPON    3   4 100    2    4
MACE            mace            WEAPON    4   5 100    4    9 speed   -1
AXE             axe             WEAPON    5   6 100    3    6
BATTLE_AXE      battle_axe      WEAPON    6   7 100    4   12 speed   -2
RUNE_SWORD      rune_sword      WEAPON    6   7  50    2    7 spirit   1
CLAYMORE        claymore        WEAPON    7  99 100    6   11 speed   -1
BROAD_SWORD     broad_sword     WEAPON    8  99 100    5   12 defense -2 speed    2
";		embedFile = StatsFile.loadFromString( "items.txt", embedText );		embedText = "Field String Class
Field Int Weight
Field String Sprite
Field String NameID
Field Int Attack
Field Int Defense
Field Int Speed
Field Int Spirit
Field Int VitalityMin
Field Int VitalityMax
Field Int DamageMin
Field Int DamageMax
Field Int XP
Field String Spell1
Field String Spell2

; Class     Wgt Sprite                   NameID             Atk Def Spd Spr V- V+ D- D+  XP Spell1           Spell2
Bandit        1 bandit_long_swords       BANDIT_CAPTAIN       2   2   8  30  2  3  1  1   5
Bandit        1 bandit_short_swords      BANDIT               2   2   5  30  3  6  1  1   5
Bandit        1 bandit_single_long_sword BANDIT               2   2   6  30  2  3  1  1   5
Bandit        1 bandit_knives            BANDIT               2   2   6  30  2  3  1  1   5

; Class     Wgt Sprite                   NameID             Atk Def Spd Spr V- V+ D- D+  XP Spell1           Spell2
Kobold        1 kobold_spear             KOBOLD_SPEAR         3   3   6   3  2  4  2  4  10
Kobold        1 kobold_knives            KOBOLD               3   3   8   3  2  6  1  4  10
Kobold        1 kobold_mage              KOBOLD_MAGE          3   3   6  12  2  6  1  3  10 TELEPORT

; Class     Wgt Sprite                   NameID             Atk Def Spd Spr V- V+ D- D+  XP Spell1           Spell2
Succubus      1 succubus                 SUCCUBUS             3   2   8   4  2  8  2  5  25 ENFEEBLE_MONSTER
Succubus      1 succubus_staff           SUCCUBUS             3   2   8   4  2  8  2  5  25 ENFEEBLE_MONSTER
Succubus      1 succubus_whip            SUCCUBUS_WHIP        3   2  10   2  2  8  2  5  25 ENFEEBLE_MONSTER
Succubus      1 succubus_scepter         SUCCUBUS             3   2   8   8  2  8  2  5  25 ENFEEBLE_MONSTER SHADOW_WALK

; Class     Wgt Sprite                   NameID             Atk Def Spd Spr V- V+ D- D+  XP Spell1           Spell2
Spider        1 spider_yellow            SPIDER               5   3   6   2  5 12  2  8  50 FREEZE
Spider        1 spider_red               SPIDER_RED           5   1   6   4 10 19  2  6  50 FREEZE
Spider        1 spider_gray              SPIDER_GRAY          5   2   9   1  5 12  2  6  50 FREEZE
Spider        1 spider_green             SPIDER               5   3   6   2  5 12  2  8  50 FREEZE

; Class     Wgt Sprite                   NameID             Atk Def Spd Spr V- V+ D- D+  XP Spell1           Spell2
Ape           1 ape_blue                 APE                  6   6  10   3  4 16  3  6 125
Ape           1 ape_black                APE                  6   6  10   3  4 16  3  6 125
Ape           1 ape_red                  APE_DEMONIC          7   8   7   3  8 20  3  6 125
Ape           1 ape_white                APE                  6   6  10   3  4 16  3  6 125

; Class     Wgt Sprite                   NameID             Atk Def Spd Spr V- V+ D- D+  XP Spell1           Spell2
Elemental     1 elemental_green          ELEMENTAL_AIR        4   4  12   6  8 26  4  8 275 FIREBALL         SHADOW_WALK
Elemental     1 elemental_white          ELEMENTAL_NATURE     4   4   8   6 14 32  4  8 275 FIREBALL         STONE_SKIN
Elemental     1 elemental_red            ELEMENTAL_SORCERY    4   4  10  18  8 26  4  8 275 MAGIC_MIRROR     TELEPORT
Elemental     1 elemental_blue           ELEMENTAL_CHAOS      4   4   8  12  8 26  4  8 275 FIREBALL

; Class     Wgt Sprite                   NameID             Atk Def Spd Spr V- V+ D- D+  XP Spell1           Spell2
Werewolf      1 werewolf_gray            WEREWOLF             5   5  12   4 12 32  4 10 500 HASTE
Werewolf      1 werewolf_blue            WEREWOLF             5   5  12   4 12 32  4 10 500 HASTE
Werewolf      1 werewolf_purple          WEREWOLF             5   5  12   4 12 32  4 10 500 HASTE

; Class     Wgt Sprite                   NameID             Atk Def Spd Spr V- V+ D- D+  XP Spell1           Spell2
Minotaur      1 minotaur                 MINOTAUR             7   6  12   4 48 72  8 14 950 BERSERK
Minotaur      1 minotaur_axe             MINOTAUR             7   6  10   4 48 72 12 18 950 BERSERK
Minotaur      1 minotaur_sword           MINOTAUR             7   6  10   4 48 72 12 18 950 BERSERK
";		embedFile = StatsFile.loadFromString( "mobs.txt", embedText );		embedText = "Field String ID
Field String Sprite
Field Int Weight
Field Int Duration
Field String Buff
Field Int BuffVal
Field String Effect
Field String EffectVal

; ID          Sprite        Weight Duration Buff      BV Effect              EV
RED_POTION    red_potion       100        0 \"\"         0 heal                full
PURPLE_POTION purple_potion     65        0 \"\"         0 charge              full
GREEN_POTION  green_potion      50       80 attack     3 \"damage multiplier\" 2
BLUE_POTION   blue_potion       50      120 defense    6
YELLOW_POTION yellow_potion     35       80 speed      6
";		embedFile = StatsFile.loadFromString( "potions.txt", embedText );		embedText = "Field String ID
Field Int Level
Field Int DamageMin
Field Int DamageMax

; ID      Lvl D- D+
FIREBALL    0  1  3
FIREBALL    1  1  4
FIREBALL    2  1  5
FIREBALL    3  2  6
FIREBALL    4  3  8
FIREBALL    5  3  9
FIREBALL    6  4 10
FIREBALL    7  4 12
FIREBALL    8  5 14";		embedFile = StatsFile.loadFromString( "spellDamage.txt", embedText );		embedText = "Field String ID
Field String Sprite
Field Int Target
Field Int Duration
Field String Stat
Field Int StatPoints
Field String Buff1
Field Int Buff1Val
Field String Buff2
Field Int Buff2Val
Field String Effect
Field String EffectVal

; Legit values for Stat are attack, defense, speed, spirit and vitality.

; Targets self.

; ID             Sprite           Tr Dur Stat    Pts. (B1 B1V B2 B2V Ef EfV)
BERSERK          berserk           0  45 attack  1080 attack 3 speed 3
BLESS_WEAPON     bless_weapon      0  60 spirit   360 attack 3
HASTE            haste             0  60 spirit   540 speed  5
SHADOW_WALK      shadow_walk       0  60 speed   1200 \"\" 0 \"\" 0 invisible
STONE_SKIN       stone_skin        0  60 spirit   480 defense 5 speed -1
BLINK            blink             0   0 spirit   360 \"\" 0 \"\" 0 blink
MAGIC_ARMOR      magic_armor       0  60 spirit   480 defense 3
REVEAL_MAP       reveal_map        0   0 spirit  3600 \"\" 0 \"\" 0 reveal
HEAL             heal              0  60 xp      1600 defense -3 \"\" 0 heal full

; Targets enemy.

; ID             Sprite           Tr Dur Stat   Pts. (B1 B1V B2 B2V Ef EfV)
FREEZE           freeze            1  60 spirit  360 speed -4
FIREBALL         fireball          1   0 spirit  360 
ENFEEBLE_MONSTER enfeeble_monster  1  60 spirit  360 attack -3
CHARM_MONSTER    charm_monster     1  60 spirit  720 \"\" 0 \"\" 0 charm
POLYMORPH        polymorph         1   0 spirit 1080 \"\" 0 \"\" 0 polymorph true
SLEEP            sleep             1  45 spirit  720 \"\" 0 \"\" 0 sleep
FEAR             fear              1  60 spirit  480 \"\" 0 \"\" 0 fear

; Targets empty square.

; ID             Sprite           Tr Dur Stat   Pts. (B1 B1V B2 B2V Ef EfV)
MAGIC_MIRROR     magic_mirror     2   90 spirit  720 \"\" 0 \"\" 0 magic_mirror
TELEPORT         teleport         2    0 spirit  720 \"\" 0 \"\" 0 teleport
";		embedFile = StatsFile.loadFromString( "spells.txt", embedText );		embedText = "Field String ID
Field String Data

; Class names.

FIGHTER         \"ファイター\"
WIZARD          \"ウィザード\"
THIEF           \"シーフ\"

; Item names.

BOOTS           \"逃走のブーツ\"
WINGED_SANDALS  \"エルメスのサンダル\"
TUNDRA_BOOTS    \"ツンドラトカゲのブーツ\"

LEATHER_ARMOR   \"レザーアーマー\"
BREASTPLATE     \"胸当て\"
CLOAK           \"敏捷な悪党のマント\"
FULL_PLATE_MAIL \"フルプレートメイル\"

RING            \"知性のリング\"
AMULET          \"悟りのアミュレット\"
GEMMED_AMULET   \"神秘のアミュレット\"
GEMMED_RING     \"ルビーのリング\"

CAP             \"忍耐のキャップ\"
HELM            \"頑丈なヘルム\"
FULL_HELM       \"活力のフルヘルム\"
GOLDEN_HELM     \"黄金のキングヘルム\"

GLOVE           \"機敏のグローブ\"
BRACELET        \"アキレスのブレスレット\"
GAUNTLET        \"頑強なガントレット\"

DAGGER          \"ダガー\"
SHORT_SWORD     \"ショートソード\"
STAFF           \"スタッフ\"
LONG_SWORD      \"ロングソード\"
AXE             \"アックス\"
BATTLE_AXE      \"強靭な戦斧\"
RUNE_SWORD      \"ルーンソード\"
MACE            \"野獣のメイス\"
CLAYMORE        \"クレイモア\"
BROAD_SWORD     \"マサムネ\"

; Potions.

RED_POTION      \"ポーション\"
PURPLE_POTION   \"マナポーション\"
BLUE_POTION     \"エレファントD\"
GREEN_POTION    \"タイガー一発\"
YELLOW_POTION   \"コカカクテル\"

; Spells.

BERSERK         \"バーサク\"
BLESS_WEAPON    \"ブレスウェポン\"
HASTE           \"ヘイスト\"
SHADOW_WALK     \"シャドウウォーク\"
STONE_SKIN      \"ストーンスキン\"
BLINK           \"ブリンク\"
MAGIC_ARMOR     \"マジックアーマー\"
REVEAL_MAP      \"マップ\"
HEAL            \"ヒール\"

FREEZE          \"フリーズ\"
FIREBALL        \"ファイヤーボール\"
ENFEEBLE_MONSTER \"ウィーク\"
CHARM_MONSTER   \"チャーム\"
POLYMORPH       \"トランスフォーム\"
SLEEP           \"スリープ\"
FEAR            \"フィアー\"

MAGIC_MIRROR    \"マジックミラー\"
TELEPORT        \"テレポート\"

; Mobs.

BANDIT_CAPTAIN  \"キャプテン\"
BANDIT          \"バンディット\"

KOBOLD_SPEAR    \"スピア・コボルト\"
KOBOLD          \"コボルト\"
KOBOLD_MAGE     \"コボルト・トリックスター\"

SUCCUBUS        \"サキュバス\"
SUCCUBUS_WHIP   \"ドミナトリックス\"

SPIDER          \"スパイダー\"
SPIDER_RED      \"ブラック・ウィドウ\"
SPIDER_GRAY     \"ウルフ・スパイダー\"

APE             \"エイプ\"
APE_DEMONIC     \"デーモン・エイプ\"

ELEMENTAL_AIR     \"エア・エレメンタル\"
ELEMENTAL_NATURE  \"ネイチャー・エレメンタル\"
ELEMENTAL_SORCERY \"ソーサリー・エレメンタル\"
ELEMENTAL_CHAOS   \"カオス・エレメンタル\"

WEREWOLF        \"ウェアウルフ\"

MINOTAUR        \"ミノタウロス\"

; Misc.

CHEST           \"宝箱\"

; Statistics
\"damage\"         \"ダメージ\"
\"attack\"          \"攻撃\"
\"defense\"           \"防御\"
\"life\"           \"ライフ\"
\"vitality\"           \"活力\"
\"speed\"         \"スピード\"
\"spirit\"           \"精神\"

; Special effects
\"damage multiplier\" \"クリティカル\"
\"charm\"                \"チャーム\"
\"fear\"              \"フィアー\"
\"sleep\"              \"スリープ\"
\"heal\"                \"ヒール\"
\"charge\"              \"チャージ\"

; Ingame messages.
STAT_HEALTH          \"体力\"
STAT_ATTACK          \"攻撃力\"
STAT_DEFENSE         \"防御力\"
STAT_LIFE            \"生命\"
STAT_VITALITY        \"活力\"
STAT_SPEED           \"スピード\"
STAT_SPIRIT          \"精神\"

PREFIX_SUPERB        \"上級の\"
PREFIX_WONDROUS      \"とびきりの\"
PREFIX_MAGICAL       \"魔法の\"

UI_LEVEL             \"レベル\"
UI_TIMES             \"x\"
UI_FLOOR             \"フロア\"
UI_MAP               \"マップ\"
UI_INV               \"持ち物\"
UI_CHAR              \"ステータス\"
UI_DAMAGE            \"\nダメージ\n\n\"
UI_DESTROY           \"破壊\"

POPUP_C              \"[ショートカットキー C]\"
POPUP_I              \"[ショートカットキー I]\"
POPUP_M              \"[ショートカットキー M]\"
POPUP_0              \"[ショートカットキー 0]\"
POPUP_1              \"[ショートカットキー 1]\"
POPUP_2              \"[ショートカットキー 2]\"
POPUP_3              \"[ショートカットキー 3]\"
POPUP_4              \"[ショートカットキー 4]\"
POPUP_5              \"[ショートカットキー 5]\"
POPUP_6              \"[ショートカットキー 6]\"
POPUP_7              \"[ショートカットキー 7]\"
POPUP_8              \"[ショートカットキー 8]\"
POPUP_9              \"[ショートカットキー 9]\"
POPUP_ENTER          \"[ショートカットキー enter]\"
POPUP_ESC            \"[ショートカットキー ESC]\"
POPUP_F1             \"[ショートカットキー F1]\"

POPUP_RECOVERED      \"回復\"
POPUP_EXPIRED        \"すり減る\"
POPUP_MIRROR         \"ミラー\"
POPUP_MIRROR_EXPIRED \"粉々になった\"
POPUP_INVIS_EXPIRED  \"再出現した\"
POPUP_EFFECT_EXPIRED \"尽きる\"
POPUP_INVIS_BREAK1   \"透明な\"
POPUP_INVIS_BREAK2   \"出現!\"
POPUP_INVIS_BROKEN   \"あなたが再出現\"
POPUP_CHARM_BREAK    \"チャームが破られた!\"
POPUP_FEAR_BREAK     \"フィアーが破られた!\"
POPUP_BACKSTAB       \"裏切り!\"
POPUP_BUMP1          \"あなたがぶつかったのは透明な\"
POPUP_BUMP2          \"。\"
POPUP_BUMPED         \"見つかった!\"
POPUP_INVIS          \"消えた\"
POPUP_HEALED         \"回復した\"
POPUP_CHARGED        \"チャージされた\"
POPUP_CHARM          \"チャーム\"
POPUP_FEAR           \"フィアー\"
POPUP_SLEEP          \"スリープ\"
POPUP_POLYMORPH      \"モーフ\"
POPUP_COIN           \"コイン\"
POPUP_COINS          \"コイン\"

NOTIFY_INV_FULL      \"袋がいっぱい!\"
NOTIFY_STAIRS        \"階段を発見!\"
NOTIFY_LATE_STAIRS   \"とうとう、下へ行く階段が!\"
NOTIFY_EXPLORE       \"探索を続行!\"
NOTIFY_LATE_EXPLORE  \"階段に向かって進行!\"
NOTIFY_DOWNSTAIRS    \"クリックして下の階へ\"
NOTIFY_PICK_SPACE1   \"\"
NOTIFY_PICK_SPACE2   \"を使う場所を選択してください\"
NOTIFY_PICK_TARGET1  \"\"
NOTIFY_PICK_TARGET2  \"の対象を選択してください\"
NOTIFY_GET_FIRST     \"ずっとこれが欲しかったんだ。\"
NOTIFY_GET_DUPLICATE \"これと同じものを既に持っている。\"
NOTIFY_GET_EQUAL1    \"自分の\"
NOTIFY_GET_EQUAL2    \" はこれと同じものだ。\"
NOTIFY_GET_SELLOLD1  \"今まで使っていた\"
NOTIFY_GET_SELLOLD2  \" は今すぐ売る。\"
NOTIFY_GET_SELLNEW1  \"今使っている\"
NOTIFY_GET_SELLNEW2  \" の方が全然マシだ!いらない!\"
NOTIFY_GET_STASHOLD1 \"今まで使っていた\"
NOTIFY_GET_STASHOLD2 \" は袋に入れておこう。\"
NOTIFY_GET_REDUNDANT \"袋の中にもっといいのがある。\"
NOTIFY_GET_STASHNEW1 \"この\"
NOTIFY_GET_STASHNEW2 \" は袋に入れておこう。\"
NOTIFY_GET_STASHSPELL1 \"この\"
NOTIFY_GET_STASHSPELL2 \"呪文は袋に入れておこう。\"
NOTIFY_EMPTYCELL     \"空のセルを使ってアイテムを交換する!\"

LOG_YOU_HIT          \"アタック!\"
LOG_HIT_YOU          \"くらった!\"
LOG_YOU_KILL         \"倒した!\"
LOG_KILLS_YOU        \"倒された…\"
LOG_YOU_MISS         \"ミス!\"
LOG_MISS_YOU         \"かわした!\"
LOG_EFFECT           \"特別効果を適用：\"
LOG_XP1              \"獲得\"
LOG_XP2              \"経験値\"
LOG_EXPIRED_TIMER    \"タイムリミットを解除：\"
LOG_POTION           \"ポーション使用\"

; UI - Menu
MENU_NEW_GAME        \"ニューゲーム\"
MENU_RESUME_GAME     \"ゲーム再開\"
MENU_CREDITS         \"クレジット\"
MENU_QUIT            \"終了\"
MENU_MUSIC           \"音楽\"
MENU_SOUND           \"サウンド\"
MENU_FULLSCREEN      \"リサイズ\"
MENU_WINDOWED        \"リサイズ\"
MENU_COPYRIGHT       \"Copyright 2011\"
MENU_PORTEDBY        \"Ported by\"
MENU_VERSION         \"バージョン\"
MENU_STANDALONE      \"単体バージョンをゲット：\"
MENU_UPGRADE1        \"バージョンをアップグレード：\"
MENU_UPGRADE2        \"!\"

MENU_HIGHSCORES      \"ハイスコア\"

MENU_CREATECHARACTER \"キャラクター作成\"
MENU_START           \"スタート\"
MENU_MENU            \"メニュー\"
MENU_MAIN_MENU       \"メインメニュー\"
MENU_HELP            \"ヘルプ\"
MENU_GAME_OVER       \"ゲームオーバー\"

PRELOADER1           \"やあこんにちは! 誰かがこのゲームを私の許可なくコピーしたようだ。  どこかをクリックするか、このURLをブラウザーにコピペしてください。\n\n\"
PRELOADER2           \"\n\n私のウェブサイトでこのゲームをプレイするために。  ありがとう、そして楽しんで!\"

DEMO_OVER            \"デモはここまで!\"
DEMO_OVER_MORE       \"もっとしたい？\"

INVENTORY_HINT       \"アイテム、呪文、\nポーションに\nマウスオーバーして\nそれぞれのパラメータや\n効果を確認。\"
";		embedFile = StatsFile.loadFromString( "strings.txt", embedText );	}}