// THIS FILE IS AUTOMATICALLY GENERATED FROM TEXT FILES IN /BIN. DO NOT MODIFYpackage data;/** * ... * @author randomnine */class StatsFileEmbed {	public static function loadEmbeddedFiles() 	{		var embedText:String;		var embedFile:StatsFile;		embedText = "Field String ID
Field String Name
Field String Slot
Field String Buff1
Field Int Buff1Val
Field String Buff2
Field Int Buff2Val

; ID            Name                         Slot    Buff1   V1 Buff2   V2 
BOOTS           [Boots of Escape]            SHOES   speed    1
WINGED_SANDLES  [Hermes' Sandals]            SHOES   speed    2
TUNDRA_BOOTS    [Tundra Lizard Boots]        SHOES   speed    2 defense  1

; ID            Name                         Slot    Buff1   V1 Buff2   V2 
LEATHER_ARMOR   [Leather Armor]              ARMOR   defense  1
BRESTPLATE      [Breastplate]                ARMOR   defense  2
FULL_PLATE_MAIL [Full Plate Armor]           ARMOR   defense  3
CLOAK           [Rogues' Cloak of Swiftness] ARMOR   defense  2 speed    2

; ID            Name                         Slot    Buff1   V1 Buff2   V2 
RING            [Ring of Wisdom]             JEWELRY spirit   1
AMULET          [Amulet of Enlightenment]    JEWELRY spirit   2
GEMMED_AMULET   [Supernatural Amulet]        JEWELRY spirit   2 defense  2
GEMMED_RING     [Ring of Rubies]             JEWELRY life     3 spirit   2

; ID            Name                         Slot    Buff1   V1 Buff2   V2 
CAP             [Cap of Endurance]           HAT     life     1
HELM            [Helm of Hardiness]          HAT     life     2
GOLDEN_HELM     [King's Golden Helm]         HAT     life     2 defense  3
FULL_HELM       [Full Helmet of Vitality]    HAT     life     4

; ID            Name                         Slot    Buff1   V1 Buff2   V2 
GLOVE           [Goves of Dexterity]         GLOVES  attack   1
BRACELET        [Achilles' Bracer]           GLOVES  attack   2
GAUNTLET        [Gauntlets of Sturdiness]    GLOVES  attack   2 defense  2
";		embedFile = StatsFile.loadFromString( embedText );		if ( embedFile != null ) { 			Resources.statsFiles.set( "items.txt", embedFile );		}		embedText = "Field String Class
Field Int Weight
Field String Sprite
Field String Name
Field Int Attack
Field Int Defense
Field Int Speed
Field Int Spirit
Field Int VitalityMin
Field Int VitalityMax
Field Int DamageMin
Field Int DamageMax
Field Int XP
Field String Spell1
Field String Spell2

; Class     Wgt Sprite                   Name               Atk Def Spd Spr V- V+ D- D+  XP Spell1           Spell2
Bandit        1 bandit_long_swords       [Captain]            2   2   4  30  2  3  1  1   5
Bandit        1 bandit_short_swords      [Bandit]             2   2   2  30  4  6  1  1   5
Bandit        1 bandit_single_long_sword [Bandit]             2   2   3  30  2  3  1  1   5
Bandit        1 bandit_knives            [Bandit]             2   2   3  30  2  3  1  1   5

; Class     Wgt Sprite                   Name               Atk Def Spd Spr V- V+ D- D+  XP Spell1           Spell2
Kobold        1 kobold_spear             [Spearkobold]        4   3   3   3  1  4  2  4  10
Kobold        1 kobold_knives            [Kobold]             4   3   3   3  1  4  1  3  10
Kobold        1 kobold_mage              [Kobold Trickster]   4   3   3  12  1  4  1  3  10 TELEPORT

; Class     Wgt Sprite                   Name               Atk Def Spd Spr V- V+ D- D+  XP Spell1           Spell2
Succubus      1 succubus                 [Succubus]           3   4   4   4  2  8  2  4  25 ENFEEBLE_MONSTER
Succubus      1 succubus_staff           [Succubus]           3   4   4   4  2  8  2  4  25 ENFEEBLE_MONSTER
Succubus      1 succubus_whip            [Dominatrix]         3   4   6   2  2  8  2  4  25 ENFEEBLE_MONSTER
Succubus      1 succubus_scepter         [Succubus]           3   4   4   8  2  8  2  4  25 ENFEEBLE_MONSTER SHADOW_WALK

; Class     Wgt Sprite                   Name               Atk Def Spd Spr V- V+ D- D+  XP Spell1           Spell2
Spider        1 spider_yellow            [Spider]             5   3   3   4  3 12  2  6  50 FREEZE
Spider        1 spider_red               [Black Widow]        5   1   4   7 10 19  2  6  50 FREEZE
Spider        1 spider_gray              [Wolf Spider]        5   3   6   1  3 12  2  6  50 FREEZE
Spider        1 spider_green             [Spider]             5   3   3   4  3 12  2  6  50 FREEZE

; Class     Wgt Sprite                   Name               Atk Def Spd Spr V- V+ D- D+  XP Spell1           Spell2
Ape           1 ape_blue                 [Ape]                6   6   6   3  4 16  4  6 125
Ape           1 ape_black                [Ape]                6   6   6   3  4 16  4  6 125
Ape           1 ape_red                  [Demon Ape]          7   8   3   3  8 20  4  6 125
Ape           1 ape_white                [Ape]                6   6   6   3  4 16  4  6 125

; Class     Wgt Sprite                   Name               Atk Def Spd Spr V- V+ D- D+  XP Spell1           Spell2
Elemental     1 elemental_green          [Air Elemental]      4   4   8   6  8 26  4  8 275 FIREBALL         SHADOW_WALK
Elemental     1 elemental_white          [Nature Elemental]   4   4   4   6 14 32  4  8 275 FIREBALL         STONE_SKIN
Elemental     1 elemental_red            [Sorcery Elemental]  4   4   4  18  8 26  4  8 275 MAGIC_MIRROR     TELEPORT
Elemental     1 elemental_blue           [Chaos Elemental]    4   4   4  12  8 26  4  8 275 FIREBALL

; Class     Wgt Sprite                   Name               Atk Def Spd Spr V- V+ D- D+  XP Spell1           Spell2
Werewolf      1 werewolf_gray            [Werewolf]           5   5   8   4  8 32  4  8 500 HASTE
Werewolf      1 werewolf_blue            [Werewolf]           5   5   8   4  8 32  4  8 500 HASTE
Werewolf      1 werewolf_purple          [Werewolf]           5   5   8   4  8 32  4  8 500 HASTE

; Class     Wgt Sprite                   Name               Atk Def Spd Spr V- V+ D- D+  XP Spell1           Spell2
Minotaur      1 minotaur                 [Minotaur]           7   4   7   4 24 48 12 32 950 BERSERK
Minotaur      1 minotaur_axe             [Minotaur]           7   4   7   4 24 48 12 32 950 BERSERK
Minotaur      1 minotaur_sword           [Minotaur]           7   4   7   4 24 48 12 32 950 BERSERK
";		embedFile = StatsFile.loadFromString( embedText );		if ( embedFile != null ) { 			Resources.statsFiles.set( "mobs.txt", embedFile );		}		embedText = "Field String ID
Field String Name
Field Int Duration
Field String Buff
Field Int BuffVal
Field String Effect
Field String EffectVal

; ID          Name                     Duration Buff      BV Effect             EV
GREEN_POTION  [Elixir of the Hawk]     120      attack     3
PURPLE_POTION [Elixir of the Lion]     120      []         0 [damage multipler] 2
BLUE_POTION   [Elixir of the Elephant] 120      defense    3
YELLOW_POTION [Coca-leaf Cocktail]     120      speed      3
RED_POTION    [Healiong Potion]        0        []         0 heal               full
";		embedFile = StatsFile.loadFromString( embedText );		if ( embedFile != null ) { 			Resources.statsFiles.set( "potions.txt", embedFile );		}		embedText = "Field String ID
Field String Name
Field String Slot
Field Int DamageMin
Field Int DamageMax
Field String Buff1
Field Int Buff1Val
Field String Buff2
Field Int Buff2Val

; ID            Name                         Slot    Dmg1 Dmg2 Buff1   V1 Buff2   V2 
DAGGER          [Dagger]                     WEAPON     1    2
STAFF           [Staff]                      WEAPON     1    3
SHORT_SWORD     [Short Sword]                WEAPON     1    3
LONG_SWORD      [Long Sword]                 WEAPON     2    4
AXE             [Axe]                        WEAPON     4    6
BATTLE_AXE      [Hardened Battle Axe]        WEAPON     5   12 speed   -2
MACE            [Beastly Mace]               WEAPON     4   11
CLAYMORE        [Broad Claymore]             WEAPON     6   10 speed   -1
BROAD_SWORD     [Twin Bladed Katana]         WEAPON     5   12 defense -2 speed    2
";		embedFile = StatsFile.loadFromString( embedText );		if ( embedFile != null ) { 			Resources.statsFiles.set( "weapons.txt", embedFile );		}	}}